[package]
name = "haul-gui"
description = "萬用媒體下載器"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
haul-core.workspace = true
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
